export default {
  npiEndpoints: {
    name: 'npi_endpoints',
    structure: `
      npi varchar(10),
      endpoint_type varchar(255),
      endpoint_type_description varchar(255),
      endpoint blob,
      affiliation char(1),
      endpoint_description blob,
      affiliation_legal_business_name varchar(255),
      use_code varchar(255),
      use_description varchar(255),
      other_use_description varchar(255),
      content_type varchar(255),
      content_description varchar(255),
      other_content_description varchar(255),
      affiliation_address_line_one varchar(255),
      affiliation_address_line_two varchar(255),
      affiliation_address_city varchar(255),
      affiliation_address_state varchar(255),	
      affiliation_address_country varchar(255),
      affiliation_address_postal_code varchar(255)
    `,
    fields: [
      'npi',
      'endpoint_type',
      'endpoint_type_description',
      'endpoint',
      'affiliation',
      'endpoint_description',
      'affiliation_legal_business_name',
      'use_code',
      'use_description',
      'other_use_description',
      'content_type',
      'content_description',
      'other_content_description',
      'affiliation_address_line_one',
      'affiliation_address_line_two',
      'affiliation_address_city',
      'affiliation_address_state',
      'affiliation_address_country',
      'affiliation_address_postal_code',
    ],
    ending: 'INNODB',
  },
  npiData: {
    name: 'npi_data',
    structure: `
      npi varchar(10),
      entity_type_code char(2),
      replacement_npi varchar(10),
      employer_identification_number_ein varchar(50),
      organization_name_legal_business_name varchar(100),
      last_name_legal_name varchar(100),
      first_name varchar(100),
      middle_name varchar(100),
      name_prefix_text varchar(100),
      name_suffix_text varchar(100),
      credential_text varchar(100),
      other_organization_name varchar(100),
      other_organization_name_type_code varchar(100),
      other_last_name varchar(100),
      other_first_name varchar(100),
      other_middle_name varchar(100),
      other_name_prefix_text varchar(100),
      other_name_suffix_text varchar(100),
      other_credential_text varchar(100),
      other_last_name_type_code varchar(100),
      first_line_business_address varchar(100),
      second_line_business_address varchar(100),
      business_address_city_name varchar(50),
      business_address_state_name varchar(100),
      business_address_postal_code varchar(20),
      business_address_country_code varchar(100),
      business_address_telephone_number varchar(16),
      business_address_fax_number varchar(16),
      first_line_business_practice_address varchar(100),
      second_line_business_practice_address varchar(100),
      business_practice_address_city_name varchar(50),
      business_practice_address_state_name varchar(100),
      business_practice_address_postal_code varchar(20),
      business_practice_address_country_code varchar(100),
      business_practice_address_telephone_number varchar(16),
      business_practice_address_fax_number varchar(16),
      enumeration_date varchar(25),
      last_update_date varchar(25),
      npi_deactivation_reason_code varchar(20),
      npi_deactivation_date varchar(25),
      npi_reactivation_date varchar(25),
      provider_gender_code varchar(10),
      authorized_official_last_name varchar(100),
      authorized_official_first_name varchar(100),
      authorized_official_middle_name varchar(100),
      authorized_official_title_or_position varchar(100),
      authorized_official_telephone_number varchar(16),
      healthcare_provider_taxonomy_code_1 varchar(25),
      provider_license_number_1 varchar(25),
      provider_license_number_state_code_1  char(11),
      healthcare_provider_primary_taxonomy_switch_1 varchar(1),
      healthcare_provider_taxonomy_code_2 varchar(25),
      provider_license_number_2 varchar(25),
      provider_license_number_state_code_2  char(11),
      healthcare_provider_primary_taxonomy_switch_2 varchar(1),
      healthcare_provider_taxonomy_code_3 varchar(25),
      provider_license_number_3 varchar(25),
      provider_license_number_state_code_3  char(11),
      healthcare_provider_primary_taxonomy_switch_3 varchar(1),
      healthcare_provider_taxonomy_code_4 varchar(25),
      provider_license_number_4 varchar(25),
      provider_license_number_state_code_4  char(11),
      healthcare_provider_primary_taxonomy_switch_4 varchar(1),
      healthcare_provider_taxonomy_code_5 varchar(25),
      provider_license_number_5 varchar(25),
      provider_license_number_state_code_5  char(11),
      healthcare_provider_primary_taxonomy_switch_5 varchar(1),
      healthcare_provider_taxonomy_code_6 varchar(25),
      provider_license_number_6 varchar(25),
      provider_license_number_state_code_6  char(11),
      healthcare_provider_primary_taxonomy_switch_6 varchar(1),
      healthcare_provider_taxonomy_code_7 varchar(25),
      provider_license_number_7 varchar(25),
      provider_license_number_state_code_7  char(11),
      healthcare_provider_primary_taxonomy_switch_7 varchar(1),
      healthcare_provider_taxonomy_code_8 varchar(25),
      provider_license_number_8 varchar(25),
      provider_license_number_state_code_8  char(11),
      healthcare_provider_primary_taxonomy_switch_8 varchar(1),
      healthcare_provider_taxonomy_code_9 varchar(25),
      provider_license_number_9 varchar(25),
      provider_license_number_state_code_9  char(11),
      healthcare_provider_primary_taxonomy_switch_9 varchar(1),
      healthcare_provider_taxonomy_code_10 varchar(25),
      provider_license_number_10 varchar(25),
      provider_license_number_state_code_10 char(11),
      healthcare_provider_primary_taxonomy_switch_10 char(1),
      healthcare_provider_taxonomy_code_11 varchar(25),
      provider_license_number_11 varchar(25),
      provider_license_number_state_code_11 char(11),
      healthcare_provider_primary_taxonomy_switch_11 char(1),
      healthcare_provider_taxonomy_code_12 varchar(25),
      provider_license_number_12 varchar(25),
      provider_license_number_state_code_12 char(11),
      healthcare_provider_primary_taxonomy_switch_12 char(1),
      healthcare_provider_taxonomy_code_13 varchar(25),
      provider_license_number_13 varchar(25),
      provider_license_number_state_code_13 char(11),
      healthcare_provider_primary_taxonomy_switch_13 char(1),
      healthcare_provider_taxonomy_code_14 varchar(25),
      provider_license_number_14 varchar(25),
      provider_license_number_state_code_14 char(11),
      healthcare_provider_primary_taxonomy_switch_14 char(1),
      healthcare_provider_taxonomy_code_15 varchar(25),
      provider_license_number_15 varchar(25),
      provider_license_number_state_code_15 char(11),
      healthcare_provider_primary_taxonomy_switch_15 char(1),
      other_provider_identifier_1 varchar(50),
      other_provider_identifier_type_code_1 varchar(50),
      other_provider_identifier_state_1 varchar(2),
      other_provider_identifier_issuer_1 varchar(50),
      other_provider_identifier_2 varchar(50),
      other_provider_identifier_type_code_2 varchar(50),
      other_provider_identifier_state_2 varchar(2),
      other_provider_identifier_issuer_2 varchar(50),
      other_provider_identifier_3 varchar(50),
      other_provider_identifier_type_code_3 varchar(50),
      other_provider_identifier_state_3 varchar(2),
      other_provider_identifier_issuer_3 varchar(55),
      other_provider_identifier_4 varchar(50),
      other_provider_identifier_type_code_4 varchar(50),
      other_provider_identifier_state_4 varchar(2),
      other_provider_identifier_issuer_4 varchar(25),
      other_provider_identifier_5 varchar(50),
      other_provider_identifier_type_code_5 varchar(50),
      other_provider_identifier_state_5 varchar(2),
      other_provider_identifier_issuer_5 varchar(25),
      other_provider_identifier_6 varchar(50),
      other_provider_identifier_type_code_6 varchar(50),
      other_provider_identifier_state_6 varchar(2),
      other_provider_identifier_issuer_6 varchar(25),
      other_provider_identifier_7 varchar(50),
      other_provider_identifier_type_code_7 varchar(50),
      other_provider_identifier_state_7 varchar(2),
      other_provider_identifier_issuer_7 varchar(25),
      other_provider_identifier_8 varchar(50),
      other_provider_identifier_type_code_8 varchar(50),
      other_provider_identifier_state_8 varchar(2),
      other_provider_identifier_issuer_8 varchar(25),
      other_provider_identifier_9 varchar(50),
      other_provider_identifier_type_code_9 varchar(50),
      other_provider_identifier_state_9 varchar(2),
      other_provider_identifier_issuer_9 varchar(25),
      other_provider_identifier_10 varchar(50),
      other_provider_identifier_type_code_10 varchar(2),
      other_provider_identifier_state_10 varchar(50),
      other_provider_identifier_issuer_10 varchar(50),
      other_provider_identifier_11 varchar(50),
      other_provider_identifier_type_code_11 varchar(2),
      other_provider_identifier_state_11 varchar(50),
      other_provider_identifier_issuer_11 varchar(50),
      other_provider_identifier_12 varchar(50),
      other_provider_identifier_type_code_12 varchar(2),
      other_provider_identifier_state_12 varchar(50),
      other_provider_identifier_issuer_12 varchar(50),
      other_provider_identifier_13 varchar(50),
      other_provider_identifier_type_code_13 varchar(2),
      other_provider_identifier_state_13 varchar(50),
      other_provider_identifier_issuer_13 varchar(50),
      other_provider_identifier_14 varchar(50),
      other_provider_identifier_type_code_14 varchar(2),
      other_provider_identifier_state_14 varchar(50),
      other_provider_identifier_issuer_14 varchar(50),
      other_provider_identifier_15 varchar(50),
      other_provider_identifier_type_code_15 varchar(2),
      other_provider_identifier_state_15 varchar(50),
      other_provider_identifier_issuer_15 varchar(50),
      other_provider_identifier_16 varchar(50),
      other_provider_identifier_type_code_16 varchar(2),
      other_provider_identifier_state_16 varchar(50),
      other_provider_identifier_issuer_16 varchar(50),
      other_provider_identifier_17 varchar(50),
      other_provider_identifier_type_code_17 varchar(2),
      other_provider_identifier_state_17 varchar(50),
      other_provider_identifier_issuer_17 varchar(50),
      other_provider_identifier_18 varchar(50),
      other_provider_identifier_type_code_18 varchar(2),
      other_provider_identifier_state_18 varchar(50),
      other_provider_identifier_issuer_18 varchar(50),
      other_provider_identifier_19 varchar(50),
      other_provider_identifier_type_code_19 varchar(2),
      other_provider_identifier_state_19 varchar(50),
      other_provider_identifier_issuer_19 varchar(50),
      other_provider_identifier_20 varchar(50),
      other_provider_identifier_type_code_20 varchar(2),
      other_provider_identifier_state_20 varchar(2),
      other_provider_identifier_issuer_20 varchar(50),
      other_provider_identifier_21 varchar(2),
      other_provider_identifier_type_code_21 varchar(2),
      other_provider_identifier_state_21 varchar(2),
      other_provider_identifier_issuer_21 varchar(50),
      other_provider_identifier_22 varchar(2),
      other_provider_identifier_type_code_22 varchar(2),
      other_provider_identifier_state_22 varchar(2),
      other_provider_identifier_issuer_22 varchar(50),
      other_provider_identifier_23 varchar(2),
      other_provider_identifier_type_code_23 varchar(2),
      other_provider_identifier_state_23 varchar(2),
      other_provider_identifier_issuer_23 varchar(50),
      other_provider_identifier_24 varchar(2),
      other_provider_identifier_type_code_24 varchar(2),
      other_provider_identifier_state_24 varchar(2),
      other_provider_identifier_issuer_24 varchar(50),
      other_provider_identifier_25 char(2),
      other_provider_identifier_type_code_25 char(2),
      other_provider_identifier_state_25 char(2),
      other_provider_identifier_issuer_25 char(2),
      other_provider_identifier_26 char(2),
      other_provider_identifier_type_code_26 char(2),
      other_provider_identifier_state_26 char(2),
      other_provider_identifier_issuer_26 char(2),
      other_provider_identifier_27 char(2),
      other_provider_identifier_type_code_27 char(2),
      other_provider_identifier_state_27 char(2),
      other_provider_identifier_issuer_27 char(2),
      other_provider_identifier_28 char(2),
      other_provider_identifier_type_code_28 char(2),
      other_provider_identifier_state_28 char(2),
      other_provider_identifier_issuer_28 char(2),
      other_provider_identifier_29 char(2),
      other_provider_identifier_type_code_29 char(2),
      other_provider_identifier_state_29 char(2),
      other_provider_identifier_issuer_29 char(2),
      other_provider_identifier_30 char(2),
      other_provider_identifier_type_code_30 char(2),
      other_provider_identifier_state_30 char(2),
      other_provider_identifier_issuer_30 char(2),
      other_provider_identifier_31 char(2),
      other_provider_identifier_type_code_31 char(2),
      other_provider_identifier_state_31 char(2),
      other_provider_identifier_issuer_31 char(2),
      other_provider_identifier_32 char(2),
      other_provider_identifier_type_code_32 char(2),
      other_provider_identifier_state_32 char(2),
      other_provider_identifier_issuer_32 char(2),
      other_provider_identifier_33 char(2),
      other_provider_identifier_type_code_33 char(2),
      other_provider_identifier_state_33 char(2),
      other_provider_identifier_issuer_33 char(2),
      other_provider_identifier_34 char(2),
      other_provider_identifier_type_code_34 char(2),
      other_provider_identifier_state_34 char(2),
      other_provider_identifier_issuer_34 char(2),
      other_provider_identifier_35 char(2),
      other_provider_identifier_type_code_35 char(2),
      other_provider_identifier_state_35 char(2),
      other_provider_identifier_issuer_35 char(2),
      other_provider_identifier_36 char(2),
      other_provider_identifier_type_code_36 char(2),
      other_provider_identifier_state_36 char(2),
      other_provider_identifier_issuer_36 char(2),
      other_provider_identifier_37 char(2),
      other_provider_identifier_type_code_37 char(2),
      other_provider_identifier_state_37 char(2),
      other_provider_identifier_issuer_37 char(2),
      other_provider_identifier_38 char(2),
      other_provider_identifier_type_code_38 char(2),
      other_provider_identifier_state_38 char(2),
      other_provider_identifier_issuer_38 char(2),
      other_provider_identifier_39 char(2),
      other_provider_identifier_type_code_39 char(2),
      other_provider_identifier_state_39 char(2),
      other_provider_identifier_issuer_39 char(2),
      other_provider_identifier_40 char(2),
      other_provider_identifier_type_code_40 char(2),
      other_provider_identifier_state_40 char(2),
      other_provider_identifier_issuer_40 char(2),
      other_provider_identifier_41 char(2),
      other_provider_identifier_type_code_41 char(2),
      other_provider_identifier_state_41 char(2),
      other_provider_identifier_issuer_41 char(2),
      other_provider_identifier_42 char(2),
      other_provider_identifier_type_code_42 char(2),
      other_provider_identifier_state_42 char(2),
      other_provider_identifier_issuer_42 char(2),
      other_provider_identifier_43 char(2),
      other_provider_identifier_type_code_43 char(2),
      other_provider_identifier_state_43 char(2),
      other_provider_identifier_issuer_43 char(2),
      other_provider_identifier_44 char(2),
      other_provider_identifier_type_code_44 char(2),
      other_provider_identifier_state_44 char(2),
      other_provider_identifier_issuer_44 char(2),
      other_provider_identifier_45 char(2),
      other_provider_identifier_type_code_45 char(2),
      other_provider_identifier_state_45 char(2),
      other_provider_identifier_issuer_45 char(2),
      other_provider_identifier_46 char(2),
      other_provider_identifier_type_code_46 char(2),
      other_provider_identifier_state_46 char(2),
      other_provider_identifier_issuer_46 char(2),
      other_provider_identifier_47 char(2),
      other_provider_identifier_type_code_47 char(2),
      other_provider_identifier_state_47 char(2),
      other_provider_identifier_issuer_47 char(2),
      other_provider_identifier_48 char(2),
      other_provider_identifier_type_code_48 char(2),
      other_provider_identifier_state_48 char(2),
      other_provider_identifier_issuer_48 char(2),
      other_provider_identifier_49 char(2),
      other_provider_identifier_type_code_49 char(2),
      other_provider_identifier_state_49 char(2),
      other_provider_identifier_issuer_49 char(2),
      other_provider_identifier_50 char(2),
      other_provider_identifier_type_code_50 char(2),
      other_provider_identifier_state_50 char(2),
      other_provider_identifier_issuer_50 char(2),
      is_sole_proprietor char(1),
      is_organization_subpart char(1),
      parent_organization_lbn varchar(50),
      parent_organization_tin varchar(50),
      authorized_official_name_prefix_text varchar(255),
      authorized_official_name_suffix_text varchar(255),
      authorized_official_credential_text varchar(255),
      healthcare_provider_taxonomy_group_1 varchar(50),
      healthcare_provider_taxonomy_group_2 varchar(50),
      healthcare_provider_taxonomy_group_3 varchar(50),
      healthcare_provider_taxonomy_group_4 varchar(50),
      healthcare_provider_taxonomy_group_5 varchar(50),
      healthcare_provider_taxonomy_group_6 varchar(50),
      healthcare_provider_taxonomy_group_7 varchar(50),
      healthcare_provider_taxonomy_group_8 varchar(50),
      healthcare_provider_taxonomy_group_9 varchar(50),
      healthcare_provider_taxonomy_group_10 varchar(50),
      healthcare_provider_taxonomy_group_11 varchar(50),
      healthcare_provider_taxonomy_group_12 varchar(50),
      healthcare_provider_taxonomy_group_13 varchar(50),
      healthcare_provider_taxonomy_group_14 varchar(50),
      healthcare_provider_taxonomy_group_15 varchar(50),
      certification_date varchar(25)
    `,
    fields: [
      "npi",
      "entity_type_code",
      "replacement_npi",
      "employer_identification_number_ein",
      "organization_name_legal_business_name",
      "last_name_legal_name",
      "first_name",
      "middle_name",
      "name_prefix_text",
      "name_suffix_text",
      "credential_text",
      "other_organization_name",
      "other_organization_name_type_code",
      "other_last_name",
      "other_first_name",
      "other_middle_name",
      "other_name_prefix_text",
      "other_name_suffix_text",
      "other_credential_text",
      "other_last_name_type_code",
      "first_line_business_address",
      "second_line_business_address",
      "business_address_city_name",
      "business_address_state_name",
      "business_address_postal_code",
      "business_address_country_code",
      "business_address_telephone_number",
      "business_address_fax_number",
      "first_line_business_practice_address",
      "second_line_business_practice_address",
      "business_practice_address_city_name",
      "business_practice_address_state_name",
      "business_practice_address_postal_code",
      "business_practice_address_country_code",
      "business_practice_address_telephone_number",
      "business_practice_address_fax_number",
      "enumeration_date",
      "last_update_date",
      "npi_deactivation_reason_code",
      "npi_deactivation_date",
      "npi_reactivation_date",
      "provider_gender_code",
      "authorized_official_last_name",
      "authorized_official_first_name",
      "authorized_official_middle_name",
      "authorized_official_title_or_position",
      "authorized_official_telephone_number",
      "healthcare_provider_taxonomy_code_1",
      "provider_license_number_1",
      "provider_license_number_state_code_1",
      "healthcare_provider_primary_taxonomy_switch_1",
      "healthcare_provider_taxonomy_code_2",
      "provider_license_number_2",
      "provider_license_number_state_code_2",
      "healthcare_provider_primary_taxonomy_switch_2",
      "healthcare_provider_taxonomy_code_3",
      "provider_license_number_3",
      "provider_license_number_state_code_3",
      "healthcare_provider_primary_taxonomy_switch_3",
      "healthcare_provider_taxonomy_code_4",
      "provider_license_number_4",
      "provider_license_number_state_code_4",
      "healthcare_provider_primary_taxonomy_switch_4",
      "healthcare_provider_taxonomy_code_5",
      "provider_license_number_5",
      "provider_license_number_state_code_5",
      "healthcare_provider_primary_taxonomy_switch_5",
      "healthcare_provider_taxonomy_code_6",
      "provider_license_number_6",
      "provider_license_number_state_code_6",
      "healthcare_provider_primary_taxonomy_switch_6",
      "healthcare_provider_taxonomy_code_7",
      "provider_license_number_7",
      "provider_license_number_state_code_7",
      "healthcare_provider_primary_taxonomy_switch_7",
      "healthcare_provider_taxonomy_code_8",
      "provider_license_number_8",
      "provider_license_number_state_code_8",
      "healthcare_provider_primary_taxonomy_switch_8",
      "healthcare_provider_taxonomy_code_9",
      "provider_license_number_9",
      "provider_license_number_state_code_9",
      "healthcare_provider_primary_taxonomy_switch_9",
      "healthcare_provider_taxonomy_code_10",
      "provider_license_number_10",
      "provider_license_number_state_code_10",
      "healthcare_provider_primary_taxonomy_switch_10",
      "healthcare_provider_taxonomy_code_11",
      "provider_license_number_11",
      "provider_license_number_state_code_11",
      "healthcare_provider_primary_taxonomy_switch_11",
      "healthcare_provider_taxonomy_code_12",
      "provider_license_number_12",
      "provider_license_number_state_code_12",
      "healthcare_provider_primary_taxonomy_switch_12",
      "healthcare_provider_taxonomy_code_13",
      "provider_license_number_13",
      "provider_license_number_state_code_13",
      "healthcare_provider_primary_taxonomy_switch_13",
      "healthcare_provider_taxonomy_code_14",
      "provider_license_number_14",
      "provider_license_number_state_code_14",
      "healthcare_provider_primary_taxonomy_switch_14",
      "healthcare_provider_taxonomy_code_15",
      "provider_license_number_15",
      "provider_license_number_state_code_15",
      "healthcare_provider_primary_taxonomy_switch_15",
      "other_provider_identifier_1",
      "other_provider_identifier_type_code_1",
      "other_provider_identifier_state_1",
      "other_provider_identifier_issuer_1",
      "other_provider_identifier_2",
      "other_provider_identifier_type_code_2",
      "other_provider_identifier_state_2",
      "other_provider_identifier_issuer_2",
      "other_provider_identifier_3",
      "other_provider_identifier_type_code_3",
      "other_provider_identifier_state_3",
      "other_provider_identifier_issuer_3",
      "other_provider_identifier_4",
      "other_provider_identifier_type_code_4",
      "other_provider_identifier_state_4",
      "other_provider_identifier_issuer_4",
      "other_provider_identifier_5",
      "other_provider_identifier_type_code_5",
      "other_provider_identifier_state_5",
      "other_provider_identifier_issuer_5",
      "other_provider_identifier_6",
      "other_provider_identifier_type_code_6",
      "other_provider_identifier_state_6",
      "other_provider_identifier_issuer_6",
      "other_provider_identifier_7",
      "other_provider_identifier_type_code_7",
      "other_provider_identifier_state_7",
      "other_provider_identifier_issuer_7",
      "other_provider_identifier_8",
      "other_provider_identifier_type_code_8",
      "other_provider_identifier_state_8",
      "other_provider_identifier_issuer_8",
      "other_provider_identifier_9",
      "other_provider_identifier_type_code_9",
      "other_provider_identifier_state_9",
      "other_provider_identifier_issuer_9",
      "other_provider_identifier_10",
      "other_provider_identifier_type_code_10",
      "other_provider_identifier_state_10",
      "other_provider_identifier_issuer_10",
      "other_provider_identifier_11",
      "other_provider_identifier_type_code_11",
      "other_provider_identifier_state_11",
      "other_provider_identifier_issuer_11",
      "other_provider_identifier_12",
      "other_provider_identifier_type_code_12",
      "other_provider_identifier_state_12",
      "other_provider_identifier_issuer_12",
      "other_provider_identifier_13",
      "other_provider_identifier_type_code_13",
      "other_provider_identifier_state_13",
      "other_provider_identifier_issuer_13",
      "other_provider_identifier_14",
      "other_provider_identifier_type_code_14",
      "other_provider_identifier_state_14",
      "other_provider_identifier_issuer_14",
      "other_provider_identifier_15",
      "other_provider_identifier_type_code_15",
      "other_provider_identifier_state_15",
      "other_provider_identifier_issuer_15",
      "other_provider_identifier_16",
      "other_provider_identifier_type_code_16",
      "other_provider_identifier_state_16",
      "other_provider_identifier_issuer_16",
      "other_provider_identifier_17",
      "other_provider_identifier_type_code_17",
      "other_provider_identifier_state_17",
      "other_provider_identifier_issuer_17",
      "other_provider_identifier_18",
      "other_provider_identifier_type_code_18",
      "other_provider_identifier_state_18",
      "other_provider_identifier_issuer_18",
      "other_provider_identifier_19",
      "other_provider_identifier_type_code_19",
      "other_provider_identifier_state_19",
      "other_provider_identifier_issuer_19",
      "other_provider_identifier_20",
      "other_provider_identifier_type_code_20",
      "other_provider_identifier_state_20",
      "other_provider_identifier_issuer_20",
      "other_provider_identifier_21",
      "other_provider_identifier_type_code_21",
      "other_provider_identifier_state_21",
      "other_provider_identifier_issuer_21",
      "other_provider_identifier_22",
      "other_provider_identifier_type_code_22",
      "other_provider_identifier_state_22",
      "other_provider_identifier_issuer_22",
      "other_provider_identifier_23",
      "other_provider_identifier_type_code_23",
      "other_provider_identifier_state_23",
      "other_provider_identifier_issuer_23",
      "other_provider_identifier_24",
      "other_provider_identifier_type_code_24",
      "other_provider_identifier_state_24",
      "other_provider_identifier_issuer_24",
      "other_provider_identifier_25",
      "other_provider_identifier_type_code_25",
      "other_provider_identifier_state_25",
      "other_provider_identifier_issuer_25",
      "other_provider_identifier_26",
      "other_provider_identifier_type_code_26",
      "other_provider_identifier_state_26",
      "other_provider_identifier_issuer_26",
      "other_provider_identifier_27",
      "other_provider_identifier_type_code_27",
      "other_provider_identifier_state_27",
      "other_provider_identifier_issuer_27",
      "other_provider_identifier_28",
      "other_provider_identifier_type_code_28",
      "other_provider_identifier_state_28",
      "other_provider_identifier_issuer_28",
      "other_provider_identifier_29",
      "other_provider_identifier_type_code_29",
      "other_provider_identifier_state_29",
      "other_provider_identifier_issuer_29",
      "other_provider_identifier_30",
      "other_provider_identifier_type_code_30",
      "other_provider_identifier_state_30",
      "other_provider_identifier_issuer_30",
      "other_provider_identifier_31",
      "other_provider_identifier_type_code_31",
      "other_provider_identifier_state_31",
      "other_provider_identifier_issuer_31",
      "other_provider_identifier_32",
      "other_provider_identifier_type_code_32",
      "other_provider_identifier_state_32",
      "other_provider_identifier_issuer_32",
      "other_provider_identifier_33",
      "other_provider_identifier_type_code_33",
      "other_provider_identifier_state_33",
      "other_provider_identifier_issuer_33",
      "other_provider_identifier_34",
      "other_provider_identifier_type_code_34",
      "other_provider_identifier_state_34",
      "other_provider_identifier_issuer_34",
      "other_provider_identifier_35",
      "other_provider_identifier_type_code_35",
      "other_provider_identifier_state_35",
      "other_provider_identifier_issuer_35",
      "other_provider_identifier_36",
      "other_provider_identifier_type_code_36",
      "other_provider_identifier_state_36",
      "other_provider_identifier_issuer_36",
      "other_provider_identifier_37",
      "other_provider_identifier_type_code_37",
      "other_provider_identifier_state_37",
      "other_provider_identifier_issuer_37",
      "other_provider_identifier_38",
      "other_provider_identifier_type_code_38",
      "other_provider_identifier_state_38",
      "other_provider_identifier_issuer_38",
      "other_provider_identifier_39",
      "other_provider_identifier_type_code_39",
      "other_provider_identifier_state_39",
      "other_provider_identifier_issuer_39",
      "other_provider_identifier_40",
      "other_provider_identifier_type_code_40",
      "other_provider_identifier_state_40",
      "other_provider_identifier_issuer_40",
      "other_provider_identifier_41",
      "other_provider_identifier_type_code_41",
      "other_provider_identifier_state_41",
      "other_provider_identifier_issuer_41",
      "other_provider_identifier_42",
      "other_provider_identifier_type_code_42",
      "other_provider_identifier_state_42",
      "other_provider_identifier_issuer_42",
      "other_provider_identifier_43",
      "other_provider_identifier_type_code_43",
      "other_provider_identifier_state_43",
      "other_provider_identifier_issuer_43",
      "other_provider_identifier_44",
      "other_provider_identifier_type_code_44",
      "other_provider_identifier_state_44",
      "other_provider_identifier_issuer_44",
      "other_provider_identifier_45",
      "other_provider_identifier_type_code_45",
      "other_provider_identifier_state_45",
      "other_provider_identifier_issuer_45",
      "other_provider_identifier_46",
      "other_provider_identifier_type_code_46",
      "other_provider_identifier_state_46",
      "other_provider_identifier_issuer_46",
      "other_provider_identifier_47",
      "other_provider_identifier_type_code_47",
      "other_provider_identifier_state_47",
      "other_provider_identifier_issuer_47",
      "other_provider_identifier_48",
      "other_provider_identifier_type_code_48",
      "other_provider_identifier_state_48",
      "other_provider_identifier_issuer_48",
      "other_provider_identifier_49",
      "other_provider_identifier_type_code_49",
      "other_provider_identifier_state_49",
      "other_provider_identifier_issuer_49",
      "other_provider_identifier_50",
      "other_provider_identifier_type_code_50",
      "other_provider_identifier_state_50",
      "other_provider_identifier_issuer_50",
      "is_sole_proprietor",
      "is_organization_subpart",
      "parent_organization_lbn",
      "parent_organization_tin",
      "authorized_official_name_prefix_text",
      "authorized_official_name_suffix_text",
      "authorized_official_credential_text",
      "healthcare_provider_taxonomy_group_1",
      "healthcare_provider_taxonomy_group_2",
      "healthcare_provider_taxonomy_group_3",
      "healthcare_provider_taxonomy_group_4",
      "healthcare_provider_taxonomy_group_5",
      "healthcare_provider_taxonomy_group_6",
      "healthcare_provider_taxonomy_group_7",
      "healthcare_provider_taxonomy_group_8",
      "healthcare_provider_taxonomy_group_9",
      "healthcare_provider_taxonomy_group_10",
      "healthcare_provider_taxonomy_group_11",
      "healthcare_provider_taxonomy_group_12",
      "healthcare_provider_taxonomy_group_13",
      "healthcare_provider_taxonomy_group_14",
      "healthcare_provider_taxonomy_group_15",
      "certification_date",
    ],
    engine: 'MyISAM',
  },
  npiOther: {
    name: 'npi_other',
    structure: `
      npi varchar(10),
      provider_other_org_name varchar(255),
      provider_other_org_type_code varchar(255)
    `,
    fields: [
      'npi',
      'provider_other_org_name',
      'provider_other_org_type_code',
    ],
    ending: 'INNODB',
  },
  npiPractice: {
    name: 'npi_practice',
    structure: `
      npi varchar(10),
      provider_secondary_location_address_address_line_1 varchar(255),
      provider_secondary_location_address_address_line_2 varchar(255),
      provider_secondary_location_address_city_name varchar(255),
      provider_secondary_location_address_state_name varchar(255),
      provider_secondary_location_address_postal_code varchar(255),
      provider_secondary_location_address_country_code varchar(255),
      provider_secondary_location_address_telephone_number varchar(255),
      provider_secondary_location_address_telephone_extension varchar(255),
      provider_location_address_fax_number varchar(255)
    `,
    fields: [
      'npi',
      'provider_secondary_location_address_address_line_1',
      'provider_secondary_location_address_address_line_2',
      'provider_secondary_location_address_city_name',
      'provider_secondary_location_address_state_name',
      'provider_secondary_location_address_postal_code',
      'provider_secondary_location_address_country_code',
      'provider_secondary_location_address_telephone_number',
      'provider_secondary_location_address_telephone_extension',
      'provider_location_address_fax_number',
    ],
    ending: 'INNODB',
  },
};
